project:
  type: website

website:
  title: "Beyond the Classroom"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: data_critique.qmd
        text: Data Critique
      - href: rq1.qmd
        text: Research Question 1
      - href: rq2.qmd
        text: Research Question 2
      - href: rq3.qmd
        text: Research Question 3
      - href: viz.qmd
        text: Visualizations
      - href: sources.qmd
        text: Sources
        

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

